### ISSUE TITLE
Binius: highly efficient proofs over binary fields 文章翻译用 SNARK 还是 SNARKs？

### ISSUE THREAD

**Issue by wenjin1997** [langlands-io/Blog#3]
在文章 [Binius: highly efficient proofs over binary fields](https://vitalik.eth.limo/general/2024/04/29/binius.html) 中，例如原文为：
> This post is primarily intended for readers roughly familiar with 2019-era cryptography, especially [SNARKs](https://vitalik.eth.limo/general/2021/01/26/snarks.html) and [STARKs](https://vitalik.eth.limo/general/2018/07/21/starks_part_3.html).

翻译1:

> 这篇文章主要面向大致熟悉 2019 年密码学的读者，尤其是 [SNARK](https://vitalik.eth.limo/general/2021/01/26/snarks.html) 和 [STARK](https://vitalik.eth.limo/general/2018/07/21/starks_part_3.html)。

翻译2：

> 这篇文章主要面向大致熟悉 2019 年密码学的读者，尤其是 [SNARKs](https://vitalik.eth.limo/general/2021/01/26/snarks.html) 和 [STARKs](https://vitalik.eth.limo/general/2018/07/21/starks_part_3.html)。

想探讨下两种翻译方式哪个更好？

我个人认为翻译2更好，原因是：
* SNARKs 和 STARKs 表达了一类这样的零知识证明协议，表示有很多个，用复数进行了表示。
* 加了"s"的这两个词与原文也一一对应，不失原文的准确性。

参考中文博客文章[一文读懂零知识证明技术 zk-SNARKs 和 zk-STARKS 的区别](https://foresightnews.pro/article/detail/29506)，文中既有 SNARK ，又有 SNARKs 。

PS：欢迎讨论与批评指正。:)

**Comment by HaroldGin931** [comment]
用s确实更好 我个人不太注意复数形式 感谢指正

**Comment by HaroldGin931** [comment]
__
